model:
  TYPE: LT # or OPTREE
  BST_DEPTH: 3
  LINEAR: True
  SPLIT: linear
  COMP: concatenate

training:
  SEED: 2020
  LR: 0.5
  ITER: 1e4
  REG: 0.001
  TWO_PHASED: False

dataset:
  DISTR: xor # or swissroll
  N: 200 # number of training points